2015-11-04 01:13:52 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Articles could not be found.
Exception Attributes: array (
  'class' => 'Articles',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cake2/articles
Stack Trace:
#0 C:\xampp\htdocs\cake2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-11-04 01:14:12 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Articles could not be found.
Exception Attributes: array (
  'class' => 'Articles',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cake2/articles
Stack Trace:
#0 C:\xampp\htdocs\cake2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-11-04 01:15:29 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Articles could not be found.
Exception Attributes: array (
  'class' => 'Articles',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cake2/articles
Stack Trace:
#0 C:\xampp\htdocs\cake2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-11-04 01:16:36 Error: [Cake\Controller\Exception\MissingActionException] Action ArticlesController::index() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ArticlesController',
  'action' => 'index',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cake2/articles
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ArticlesController))
#2 C:\xampp\htdocs\cake2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-11-04 01:17:46 Error: [Cake\Database\Exception] SQLSTATE[42S02]: Base table or view not found: 1146 Table 'conestoga_pizza.articles' doesn't exist
Request URL: /cake2/articles
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Schema\Collection.php(96): Cake\Database\Schema\Collection->_reflect('Column', 'articles', Array, Object(Cake\Database\Schema\Table))
#1 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Schema\CachedCollection.php(64): Cake\Database\Schema\Collection->describe('articles', Array)
#2 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\ORM\Table.php(423): Cake\Database\Schema\CachedCollection->describe('articles')
#3 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\ORM\Query.php(173): Cake\ORM\Table->schema()
#4 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\ORM\Query.php(131): Cake\ORM\Query->addDefaultTypes(Object(App\Model\table\ArticlesTable))
#5 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\ORM\Table.php(1228): Cake\ORM\Query->__construct(Object(Cake\Database\Connection), Object(App\Model\table\ArticlesTable))
#6 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\ORM\Table.php(931): Cake\ORM\Table->query()
#7 C:\xampp\htdocs\cake2\src\Controller\ArticlesController.php(9): Cake\ORM\Table->find('all')
#8 [internal function]: App\Controller\ArticlesController->index()
#9 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#11 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ArticlesController))
#12 C:\xampp\htdocs\cake2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#13 {main}


2015-11-04 01:25:48 Error: Fatal Error (1): Call to a member function format() on null in [C:\xampp\htdocs\cake2\src\Template\Articles\index.ctp, line 21]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-04 01:25:48 Error: [Cake\Error\FatalErrorException] Call to a member function format() on null
Request URL: /cake2/articles
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 21)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-04 03:39:08 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Articles could not be found.
Exception Attributes: array (
  'class' => 'Articles',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cake2/articles
Stack Trace:
#0 C:\xampp\htdocs\cake2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-11-04 03:41:34 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Articles could not be found.
Exception Attributes: array (
  'class' => 'Articles',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cake2/articles
Stack Trace:
#0 C:\xampp\htdocs\cake2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-11-04 03:41:57 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Customer could not be found.
Exception Attributes: array (
  'class' => 'Customer',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cake2/customer
Stack Trace:
#0 C:\xampp\htdocs\cake2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-11-04 03:42:29 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\cake2\src\Controller\CustomerController.php, line 9]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-04 03:42:29 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /cake2/customer
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-04 03:49:38 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\cake2\src\Controller\CustomerController.php, line 9]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-04 03:49:39 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /cake2/customer
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-04 03:51:32 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\cake2\src\Controller\CustomerController.php, line 9]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-04 03:51:32 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /cake2/Customer
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-04 04:30:04 Error: [Cake\Controller\Exception\MissingActionException] Action CustomerController::add() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'CustomerController',
  'action' => 'add',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cake2/customer/add
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CustomerController))
#2 C:\xampp\htdocs\cake2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-11-04 04:37:54 Error: Fatal Error (4): syntax error, unexpected 'return' (T_RETURN) in [C:\xampp\htdocs\cake2\src\Model\Table\CustomerTable.php, line 39]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-04 04:37:54 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'return' (T_RETURN)
Request URL: /cake2/customer
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 39)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-04 04:41:27 Error: [Cake\Controller\Exception\MissingActionException] Action CustomerController::add() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'CustomerController',
  'action' => 'add',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cake2/customer/add
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CustomerController))
#2 C:\xampp\htdocs\cake2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-11-04 04:42:01 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\cake2\src\Controller\CustomerController.php, line 27]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-04 04:42:02 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '}'
Request URL: /cake2/customer/add
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 27)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-04 04:44:36 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\cake2\src\Controller\CustomerController.php, line 25]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-04 04:44:36 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '}'
Request URL: /cake2/customer/add
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-04 04:44:47 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting ',' or ';' in [C:\xampp\htdocs\cake2\src\Template\Customer\add.ctp, line 4]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-04 04:44:47 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting ',' or ';'
Request URL: /cake2/customer/add
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 4)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-04 04:46:20 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting ',' or ';' in [C:\xampp\htdocs\cake2\src\Template\Customer\add.ctp, line 4]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-04 04:46:21 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting ',' or ';'
Request URL: /cake2/customer/add
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 4)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-04 04:46:39 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting ',' or ';' in [C:\xampp\htdocs\cake2\src\Template\Customer\add.ctp, line 4]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-04 04:46:39 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting ',' or ';'
Request URL: /cake2/customer/add
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 4)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-04 05:25:17 Error: Fatal Error (4): syntax error, unexpected '{' in [C:\xampp\htdocs\cake2\src\Controller\CustomerController.php, line 23]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-04 05:25:17 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '{'
Request URL: /cake2/customer/add
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 23)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-04 16:22:57 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Articles could not be found.
Exception Attributes: array (
  'class' => 'Articles',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cake2/articles
Stack Trace:
#0 C:\xampp\htdocs\cake2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-11-04 17:02:13 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Customer.E' in 'field list'
Request URL: /cake2/customer
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(171): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\ORM\Query.php(872): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(272): Cake\ORM\Query->_execute()
#7 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\ORM\Query.php(823): Cake\ORM\Query->_all()
#8 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(131): Cake\ORM\Query->all()
#9 C:\xampp\htdocs\cake2\src\Template\Customer\index.ctp(15): Cake\ORM\Query->getIterator()
#10 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\View\View.php(970): include('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\View\View.php(930): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#12 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\View\View.php(578): Cake\View\View->_render('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Controller\Controller.php(611): Cake\View\View->render(NULL, NULL)
#14 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#15 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CustomerController))
#16 C:\xampp\htdocs\cake2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#17 {main}


2015-11-04 17:03:47 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Customer.E' in 'field list'
Request URL: /cake2/customer
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(171): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\ORM\Query.php(872): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(272): Cake\ORM\Query->_execute()
#7 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\ORM\Query.php(823): Cake\ORM\Query->_all()
#8 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(131): Cake\ORM\Query->all()
#9 C:\xampp\htdocs\cake2\src\Template\Customer\index.ctp(15): Cake\ORM\Query->getIterator()
#10 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\View\View.php(970): include('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\View\View.php(930): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#12 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\View\View.php(578): Cake\View\View->_render('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Controller\Controller.php(611): Cake\View\View->render(NULL, NULL)
#14 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#15 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CustomerController))
#16 C:\xampp\htdocs\cake2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#17 {main}


2015-11-04 17:03:48 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Customer.E' in 'field list'
Request URL: /cake2/customer
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(171): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\ORM\Query.php(872): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(272): Cake\ORM\Query->_execute()
#7 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\ORM\Query.php(823): Cake\ORM\Query->_all()
#8 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(131): Cake\ORM\Query->all()
#9 C:\xampp\htdocs\cake2\src\Template\Customer\index.ctp(15): Cake\ORM\Query->getIterator()
#10 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\View\View.php(970): include('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\View\View.php(930): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#12 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\View\View.php(578): Cake\View\View->_render('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Controller\Controller.php(611): Cake\View\View->render(NULL, NULL)
#14 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#15 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CustomerController))
#16 C:\xampp\htdocs\cake2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#17 {main}


2015-11-04 17:04:00 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Customer.E' in 'field list'
Request URL: /cake2/customer
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(171): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\ORM\Query.php(872): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(272): Cake\ORM\Query->_execute()
#7 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\ORM\Query.php(823): Cake\ORM\Query->_all()
#8 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(131): Cake\ORM\Query->all()
#9 C:\xampp\htdocs\cake2\src\Template\Customer\index.ctp(15): Cake\ORM\Query->getIterator()
#10 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\View\View.php(970): include('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\View\View.php(930): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#12 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\View\View.php(578): Cake\View\View->_render('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Controller\Controller.php(611): Cake\View\View->render(NULL, NULL)
#14 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#15 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CustomerController))
#16 C:\xampp\htdocs\cake2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#17 {main}


2015-11-04 17:04:05 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Customer.E' in 'field list'
Request URL: /cake2/customer
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(171): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\ORM\Query.php(872): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(272): Cake\ORM\Query->_execute()
#7 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\ORM\Query.php(823): Cake\ORM\Query->_all()
#8 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(131): Cake\ORM\Query->all()
#9 C:\xampp\htdocs\cake2\src\Template\Customer\index.ctp(15): Cake\ORM\Query->getIterator()
#10 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\View\View.php(970): include('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\View\View.php(930): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#12 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\View\View.php(578): Cake\View\View->_render('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Controller\Controller.php(611): Cake\View\View->render(NULL, NULL)
#14 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#15 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CustomerController))
#16 C:\xampp\htdocs\cake2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#17 {main}


2015-11-04 17:05:12 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Customer.E' in 'field list'
Request URL: /cake2/customer
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(171): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\ORM\Query.php(872): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(272): Cake\ORM\Query->_execute()
#7 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\ORM\Query.php(823): Cake\ORM\Query->_all()
#8 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(131): Cake\ORM\Query->all()
#9 C:\xampp\htdocs\cake2\src\Template\Customer\index.ctp(15): Cake\ORM\Query->getIterator()
#10 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\View\View.php(970): include('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\View\View.php(930): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#12 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\View\View.php(578): Cake\View\View->_render('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Controller\Controller.php(611): Cake\View\View->render(NULL, NULL)
#14 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#15 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CustomerController))
#16 C:\xampp\htdocs\cake2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#17 {main}


2015-11-04 17:14:21 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'
Request URL: /cake2/customer/add
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(171): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\ORM\Table.php(1530): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->_insert(Object(Cake\ORM\Entity), Array)
#7 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(Cake\ORM\Entity), Object(ArrayObject))
#8 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Database\Connection.php(557): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#9 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#10 C:\xampp\htdocs\cake2\src\Controller\CustomerController.php(23): Cake\ORM\Table->save(Object(Cake\ORM\Entity))
#11 [internal function]: App\Controller\CustomerController->add()
#12 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#13 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#14 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CustomerController))
#15 C:\xampp\htdocs\cake2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 {main}


2015-11-04 17:32:29 Error: Fatal Error (4): syntax error, unexpected ',' in [C:\xampp\htdocs\cake2\src\Controller\CustomerController.php, line 53]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-04 17:32:30 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ','
Request URL: /cake2/customer
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 53)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-04 17:34:35 Error: Fatal Error (4): syntax error, unexpected ',' in [C:\xampp\htdocs\cake2\src\Controller\CustomerController.php, line 53]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-04 17:34:35 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ','
Request URL: /cake2/customer
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 53)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-04 17:34:57 Warning: Warning (2): Missing argument 1 for App\Controller\CustomerController::delete() in [C:\xampp\htdocs\cake2\src\Controller\CustomerController.php, line 47]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
App\Controller\CustomerController::delete() - APP/Controller\CustomerController.php, line 47
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 429
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-04 17:34:58 Error: [Cake\Datasource\Exception\InvalidPrimaryKeyException] Record not found in table "customer" with primary key [NULL]
Request URL: /cake2/customer/delete
Stack Trace:
#0 C:\xampp\htdocs\cake2\src\Controller\CustomerController.php(50): Cake\ORM\Table->get(NULL)
#1 [internal function]: App\Controller\CustomerController->delete()
#2 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CustomerController))
#5 C:\xampp\htdocs\cake2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2015-11-04 17:35:33 Error: Fatal Error (4): syntax error, unexpected ',' in [C:\xampp\htdocs\cake2\src\Controller\CustomerController.php, line 53]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-04 17:35:33 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ','
Request URL: /cake2/customer
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 53)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-04 17:35:54 Error: Fatal Error (4): syntax error, unexpected ',' in [C:\xampp\htdocs\cake2\src\Controller\CustomerController.php, line 53]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-04 17:35:55 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ','
Request URL: /cake2/customer
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 53)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-04 17:38:40 Error: Fatal Error (4): syntax error, unexpected ',' in [C:\xampp\htdocs\cake2\src\Controller\CustomerController.php, line 53]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-04 17:38:40 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ','
Request URL: /cake2/customer
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 53)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-04 17:39:04 Error: Fatal Error (4): syntax error, unexpected ',' in [C:\xampp\htdocs\cake2\src\Controller\CustomerController.php, line 53]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-04 17:39:04 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ','
Request URL: /cake2/customer
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 53)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-04 17:39:31 Error: Fatal Error (4): syntax error, unexpected ',' in [C:\xampp\htdocs\cake2\src\Controller\CustomerController.php, line 54]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-04 17:39:31 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ','
Request URL: /cake2/customer
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 54)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-04 17:47:38 Error: [Cake\Routing\Exception\MissingRouteException] A route matching "/" could not be found.
Exception Attributes: array (
  'url' => '/',
)
Request URL: /cake2/
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Router.php(338): Cake\Routing\RouteCollection->parse('/')
#1 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Filter\RoutingFilter.php(53): Cake\Routing\Router::parse(false)
#2 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\DispatcherFilter.php(145): Cake\Routing\Filter\RoutingFilter->beforeDispatch(Object(Cake\Event\Event))
#3 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Event\EventManager.php(389): Cake\Routing\DispatcherFilter->handle(Object(Cake\Event\Event), Object(Cake\Network\Request), Object(Cake\Network\Response))
#4 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Event\EventManager.php(355): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#5 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#6 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(62): Cake\Routing\Dispatcher->dispatchEvent('Dispatcher.befo...', Array)
#7 C:\xampp\htdocs\cake2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#8 {main}


2015-11-04 17:47:50 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Index could not be found.
Exception Attributes: array (
  'class' => 'Index',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cake2/index
Stack Trace:
#0 C:\xampp\htdocs\cake2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-11-04 18:25:54 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR) in [C:\xampp\htdocs\cake2\src\Model\Table\UsersTable.php, line 13]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-04 18:25:55 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR)
Request URL: /cake2/users
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-04 18:26:00 Error: [Cake\Routing\Exception\MissingControllerException] Controller class User could not be found.
Exception Attributes: array (
  'class' => 'User',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cake2/user
Stack Trace:
#0 C:\xampp\htdocs\cake2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-11-04 18:26:08 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR) in [C:\xampp\htdocs\cake2\src\Model\Table\UsersTable.php, line 13]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-04 18:26:09 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR)
Request URL: /cake2/users
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-04 18:27:03 Error: Fatal Error (4): syntax error, unexpected '>' in [C:\xampp\htdocs\cake2\src\Model\Table\UsersTable.php, line 21]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-04 18:27:04 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '>'
Request URL: /cake2/users
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 21)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-04 18:27:18 Error: [Cake\View\Exception\MissingTemplateException] Template file "Users\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\index.ctp',
)
Request URL: /cake2/users
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\View\View.php(575): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Controller\Controller.php(611): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#4 C:\xampp\htdocs\cake2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2015-11-04 18:28:59 Error: [Cake\Controller\Exception\MissingActionException] Action UsersController::login() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cake2/users/login
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#2 C:\xampp\htdocs\cake2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-11-04 18:35:48 Error: [Cake\Controller\Exception\MissingActionException] Action UsersController::login() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cake2/users/login
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#2 C:\xampp\htdocs\cake2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-11-04 18:36:56 Error: [Cake\Controller\Exception\MissingActionException] Action UsersController::login() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cake2/users/login
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#2 C:\xampp\htdocs\cake2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-11-04 18:37:06 Error: [Cake\Controller\Exception\MissingActionException] Action UsersController::login() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cake2/users/login
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#2 C:\xampp\htdocs\cake2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-11-05 01:32:59 Warning: Warning (2): Creating default object from empty value in [C:\xampp\htdocs\cake2\src\Controller\UsersController.php, line 44]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
App\Controller\UsersController::add() - APP/Controller\UsersController.php, line 44
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 429
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-05 01:54:12 Error: Fatal Error (1): Call to a member function isOwnedBy() on boolean in [C:\xampp\htdocs\cake2\src\Controller\CustomerController.php, line 73]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-05 01:54:13 Error: [Cake\Error\FatalErrorException] Call to a member function isOwnedBy() on boolean
Request URL: /cake2/customer/delete/6
Stack Trace:
#0 C:\xampp\htdocs\cake2\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 73)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


